import { useState } from 'react';
import { Pressable, Text, View } from '@/components/ui/primitives';
import { Row, Section, WorkflowShell } from '@/components/ui/WorkflowShell';
import { useLeague } from '@/lib/league-context';
import { useTheme, useThemeTokens } from '@/lib/theme';
import { Download, FileDown, Share2 } from 'lucide-react-native';

type ReportKey = 'weekly' | 'power' | 'awards' | 'trade' | 'waiver' | 'season' | 'championship';

const REPORTS: { key: ReportKey; title: string; sub: string }[] = [
  { key: 'weekly', title: 'Weekly Report', sub: "AI recap of the week's games" },
  { key: 'power', title: 'Power Rankings', sub: 'Updated every Tuesday' },
  { key: 'awards', title: 'Awards', sub: 'Player of the Week & superlatives' },
  { key: 'trade', title: 'Trade Report', sub: 'Grades & league impact' },
  { key: 'waiver', title: 'Waiver Report', sub: 'Top adds and breakouts' },
  { key: 'season', title: 'Season Report', sub: 'Trends & playoff odds' },
  { key: 'championship', title: 'Championship Report', sub: 'Final recap' },
];

export default function ReportsPage() {
  const { active } = useLeague();
  const [open, setOpen] = useState<ReportKey | null>(null);
  const { hex, surfaces } = useThemeTokens();
  const { scheme } = useTheme();
  if (!active) return null;

  if (open) {
    const r = REPORTS.find((x) => x.key === open)!;
    return <ReportDetail report={r} onBack={() => setOpen(null)} week={active.week} />;
  }

  const stage = active.stage;
  const featured: ReportKey =
    stage === 'playoffs' ? 'championship' : stage === 'regular' ? 'weekly' : 'season';

  const inkOnPrimary = scheme === 'dark' ? '20,20,20' : '252,252,252';

  return (
    <WorkflowShell title="Reports" eyebrow="Commissioner">
      <View
        style={{
          marginBottom: 20,
          borderRadius: 30,
          backgroundColor: hex.primary,
          padding: 20,
        }}
      >
        <Text variant="eyebrow" style={{ color: `rgba(${inkOnPrimary},0.6)` }}>
          New this week
        </Text>
        <Text variant="sectionTitle" style={{ marginTop: 4, color: hex.primaryForeground, fontSize: 22 }}>
          {REPORTS.find((r) => r.key === featured)?.title}
        </Text>
        <Text variant="subtitle" style={{ marginTop: 4, color: `rgba(${inkOnPrimary},0.7)` }}>
          Week {active.week} · Generated by Fantasy Doctor
        </Text>
        <Pressable
          onPress={() => setOpen(featured)}
          style={[
            surfaces.pill,
            {
              marginTop: 16,
              alignSelf: 'flex-start',
              backgroundColor: hex.background,
              paddingHorizontal: 16,
              paddingVertical: 8,
            },
          ]}
        >
          <Text variant="button">Read report</Text>
        </Pressable>
      </View>

      <Section title="All Reports">
        {REPORTS.map((r, i) => (
          <Row key={r.key} first={i === 0} label={r.title} sub={r.sub} onPress={() => setOpen(r.key)} />
        ))}
      </Section>
    </WorkflowShell>
  );
}

function ReportDetail({
  report,
  onBack,
  week,
}: {
  report: { key: ReportKey; title: string; sub: string };
  onBack: () => void;
  week: number;
}) {
  const { hex, layout, surfaces } = useThemeTokens();
  return (
    <WorkflowShell title={report.title} eyebrow="Report" onBack={onBack} backLabel="Reports">
      <View style={[surfaces.roundedCardLg, { marginBottom: 20, padding: 20 }]}>
        <Text variant="eyebrow">Summary</Text>
        <Text variant="body" style={{ marginTop: 8, lineHeight: 22 }}>
          Week {week} was defined by upsets and breakout performances. The top three teams traded
          blows while Sam Ortiz's lineup posted the highest score of the season behind two surprise
          stars. Playoff picture is tightening with three teams within half a game.
        </Text>
      </View>

      <View style={[layout.row, { marginBottom: 20, gap: 10 }]}>
        <Stat label="Top Score" value="178.4" />
        <Stat label="Closest Game" value="2.1" />
        <Stat label="MVP" value="J. Jefferson" />
      </View>

      <View style={[surfaces.card, { padding: 8 }]}>
        <Row first label="Export PDF" trailing={<FileDown size={16} color={hex.mutedForeground} />} onPress={() => {}} />
        <Row label="Share" trailing={<Share2 size={16} color={hex.mutedForeground} />} onPress={() => {}} />
        <Row label="Download" trailing={<Download size={16} color={hex.mutedForeground} />} onPress={() => {}} />
      </View>
    </WorkflowShell>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  const { hex, layout } = useThemeTokens();
  return (
    <View
      style={[
        layout.flex1,
        layout.centered,
        {
          borderRadius: 20,
          backgroundColor: hex.surfaceElevated,
          padding: 12,
        },
      ]}
    >
      <Text variant="pill" muted>
        {label}
      </Text>
      <Text variant="titleMd" style={{ marginTop: 4 }}>
        {value}
      </Text>
    </View>
  );
}
