import { useState } from 'react';
import { View } from 'react-native';
import { Download, FileDown, Share2 } from 'lucide-react-native';
import { Pressable, Text } from '@/components/ui/primitives';
import { Row, Section, WorkflowShell } from '@/components/ui/WorkflowShell';
import { useLeague } from '@/lib/league-context';
import { useColors } from '@/lib/theme';

type ReportKey = 'weekly' | 'power' | 'awards' | 'trade' | 'waiver' | 'season' | 'championship';

const REPORTS: { key: ReportKey; title: string; sub: string }[] = [
  { key: 'weekly', title: 'Weekly Report', sub: "AI recap of the week's games" },
  { key: 'power', title: 'Power Rankings', sub: 'Updated every Tuesday' },
  { key: 'awards', title: 'Awards', sub: 'Player of the Week & superlatives' },
  { key: 'trade', title: 'Trade Report', sub: 'Grades & league impact' },
  { key: 'waiver', title: 'Waiver Report', sub: 'Top adds and breakouts' },
  { key: 'season', title: 'Season Report', sub: 'Trends & playoff odds' },
  { key: 'championship', title: 'Championship Report', sub: 'Final recap' },
];

export default function ReportsPage() {
  const { active } = useLeague();
  const [open, setOpen] = useState<ReportKey | null>(null);
  if (!active) return null;

  if (open) {
    const r = REPORTS.find((x) => x.key === open)!;
    return <ReportDetail report={r} onBack={() => setOpen(null)} week={active.week} />;
  }

  const stage = active.stage;
  const featured: ReportKey =
    stage === 'playoffs' ? 'championship' : stage === 'regular' ? 'weekly' : 'season';

  return (
    <WorkflowShell title="Reports" eyebrow="Commissioner">
      <View className="mb-5 rounded-[30px] bg-foreground p-5">
        <Text className="text-[11px] uppercase tracking-widest text-background/60">New this week</Text>
        <Text className="mt-1 text-[22px] font-semibold tracking-tight text-background">
          {REPORTS.find((r) => r.key === featured)?.title}
        </Text>
        <Text className="mt-1 text-[13px] text-background/70">
          Week {active.week} · Generated by Fantasy Doctor
        </Text>
        <Pressable
          onPress={() => setOpen(featured)}
          className="mt-4 self-start rounded-full bg-background px-4 py-2"
        >
          <Text className="text-[13px] font-semibold text-foreground">Read report</Text>
        </Pressable>
      </View>

      <Section title="All Reports">
        {REPORTS.map((r, i) => (
          <Row key={r.key} first={i === 0} label={r.title} sub={r.sub} onPress={() => setOpen(r.key)} />
        ))}
      </Section>
    </WorkflowShell>
  );
}

function ReportDetail({
  report,
  onBack,
  week,
}: {
  report: { key: ReportKey; title: string; sub: string };
  onBack: () => void;
  week: number;
}) {
  const c = useColors();
  return (
    <WorkflowShell title={report.title} eyebrow="Report" onBack={onBack} backLabel="Reports">
      <View className="mb-5 rounded-[28px] bg-surface-elevated p-5">
        <Text className="text-[11px] uppercase tracking-widest text-muted-foreground">Summary</Text>
        <Text className="mt-2 text-[15px] leading-relaxed">
          Week {week} was defined by upsets and breakout performances. The top three teams traded
          blows while Sam Ortiz's lineup posted the highest score of the season behind two surprise
          stars. Playoff picture is tightening with three teams within half a game.
        </Text>
      </View>

      <View className="mb-5 flex-row gap-2.5">
        <Stat label="Top Score" value="178.4" />
        <Stat label="Closest Game" value="2.1" />
        <Stat label="MVP" value="J. Jefferson" />
      </View>

      <View className="rounded-[28px] bg-surface-elevated p-2">
        <Row first label="Export PDF" trailing={<FileDown size={16} color={c.mutedForeground} />} onPress={() => {}} />
        <Row label="Share" trailing={<Share2 size={16} color={c.mutedForeground} />} onPress={() => {}} />
        <Row label="Download" trailing={<Download size={16} color={c.mutedForeground} />} onPress={() => {}} />
      </View>
    </WorkflowShell>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <View className="flex-1 items-center rounded-[20px] bg-surface-elevated p-3">
      <Text className="text-[10px] uppercase tracking-widest text-muted-foreground">{label}</Text>
      <Text className="mt-1 text-[16px] font-semibold tracking-tight">{value}</Text>
    </View>
  );
}
